### ISSUE TITLE
Crash when clicking Search Results after opening the designer

### ISSUE THREAD

**Issue by linquize** [icsharpcode/SharpDevelop#437]
SharpDevelop Version : 5.0.0.4270-Beta 3-7d968cd0
.NET Version         : 4.0.30319.18063
OS Version           : Microsoft Windows NT 6.1.7601 Service Pack 1
Current culture      : Invariant Language (Invariant Country) ()
Current UI language  : en
Running under WOW6432, processor architecture: x86-64
Working Set Memory   : 342088kb
GC Heap Memory       : 133756kb

Unhandled WPF exception
Exception thrown:
System.Windows.Markup.XamlParseException: Set connectionId threw an exception. ---> System.InvalidCastException: [A]ICSharpCode.TreeView.SharpTreeView cannot be cast to [B]ICSharpCode.TreeView.SharpTreeView. Type A originates from 'ICSharpCode.TreeView, Version=5.0.0.4270, Culture=neutral, PublicKeyToken=f829da5c02be14ee' in the context 'LoadNeither' in a byte array. Type B originates from 'ICSharpCode.TreeView, Version=5.0.0.4270, Culture=neutral, PublicKeyToken=f829da5c02be14ee' in the context 'Default' at location 'D:\B\DotNetApps\SharpDevelop\bin\ICSharpCode.TreeView.dll'.
   at ICSharpCode.XamlBinding.XamlOutlineContentHost.System.Windows.Markup.IComponentConnector.Connect(Int32 connectionId, Object target)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetConnectionId(Object root, Int32 connectionId, Object instance)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at ICSharpCode.XamlBinding.XamlOutlineContentHost.InitializeComponent()
   at ICSharpCode.XamlBinding.XamlOutlineContentHost..ctor(ITextEditor editor)
   at ICSharpCode.XamlBinding.XamlTextEditorExtension.Attach(ITextEditor editor)
   at ICSharpCode.AvalonEdit.AddIn.CodeEditorAdapter.AttachExtensions()
   at ICSharpCode.AvalonEdit.AddIn.CodeEditorAdapter.FileNameChanged()
   at ICSharpCode.AvalonEdit.AddIn.CodeEditor.set_FileName(FileName value)
   at ICSharpCode.AvalonEdit.AddIn.AvalonEditViewContent.Load(OpenedFile file, Stream stream)
   at ICSharpCode.SharpDevelop.Workbench.OpenedFile.SwitchedToView(IViewContent newView) in d:\B\DotNetApps\SharpDevelop\src\Main\Base\Project\Workbench\File\OpenedFile.cs:line 319
   at ICSharpCode.SharpDevelop.Workbench.OpenedFile.ForceInitializeView(IViewContent view) in d:\B\DotNetApps\SharpDevelop\src\Main\Base\Project\Workbench\File\OpenedFile.cs:line 146
   at ICSharpCode.SharpDevelop.Workbench.FileServiceOpenedFile.ForceInitializeView(IViewContent view)
   at ICSharpCode.AvalonEdit.AddIn.AvalonEditViewContent..ctor(OpenedFile file, Encoding fixedEncodingForLoading)
   at ICSharpCode.AvalonEdit.AddIn.AvalonEditDisplayBinding.CreateContentForFile(OpenedFile file)
   at ICSharpCode.SharpDevelop.Workbench.FileService.LoadFileWrapper.Invoke(FileName fileName)
   at ICSharpCode.Core.FileUtility.<>c__DisplayClass13.<ObservedLoad>b__12() in d:\B\DotNetApps\SharpDevelop\src\Main\Core\Project\Src\Services\FileUtility\FileUtility.cs:line 724
   at ICSharpCode.Core.FileUtility.ObservedLoad(FileOperationDelegate loadFile, FileName fileName, String message, FileErrorPolicy policy) in d:\B\DotNetApps\SharpDevelop\src\Main\Core\Project\Src\Services\FileUtility\FileUtility.cs:line 683
   at ICSharpCode.Core.FileUtility.ObservedLoad(NamedFileOperationDelegate saveFileAs, FileName fileName, String message, FileErrorPolicy policy) in d:\B\DotNetApps\SharpDevelop\src\Main\Core\Project\Src\Services\FileUtility\FileUtility.cs:line 724
   at ICSharpCode.Core.FileUtility.ObservedLoad(NamedFileOperationDelegate saveFileAs, FileName fileName, FileErrorPolicy policy) in d:\B\DotNetApps\SharpDevelop\src\Main\Core\Project\Src\Services\FileUtility\FileUtility.cs:line 729
   at ICSharpCode.SharpDevelop.Workbench.FileService.OpenFile(FileName fileName, Boolean switchToOpenedView)
   at ICSharpCode.SharpDevelop.Workbench.FileService.JumpToFilePosition(FileName fileName, Int32 line, Int32 column)
   at SearchAndReplace.SearchResultNode.ActivateItem()
   at SearchAndReplace.ResultsTreeView.OnMouseDoubleClick(MouseButtonEventArgs e)
   at System.Windows.Controls.Control.HandleDoubleClick(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

---- Recent log messages:
19:03:16.014 [1] DEBUG - ActiveContentChanged to ICSharpCode.SharpDevelop.Gui.ErrorListPad
19:03:16.029 [1] DEBUG - ActiveContentChanged to ICSharpCode.WpfDesign.AddIn.WpfViewContent
19:03:18.207 [1] DEBUG - NavigationService
	ActiveViewContent: CodeCompletionPanelXaml.xaml
	          Subview: ${res:FormsDesigner.DesignTabPages.SourceTabPage}
19:03:18.207 [1] DEBUG - ActiveViewContentChanged to [AvalonEditViewContent D:\B\DotNetApps\SharpDevelop2\src\Main\Base\Project\Src\Editor\CodeCompletion\CodeCompletionPanelXaml.xaml]
19:03:18.207 [1] DEBUG - ActiveContentChanged to [AvalonEditViewContent D:\B\DotNetApps\SharpDevelop2\src\Main\Base\Project\Src\Editor\CodeCompletion\CodeCompletionPanelXaml.xaml]
19:03:19.931 [1] DEBUG - Saving memento of '[AvalonEditViewContent D:\B\DotNetApps\SharpDevelop2\src\Main\Base\Project\Src\Editor\CodeCompletion\CodeCompletionPanelXaml.xaml]' to key '1e13ec5:D:\B\DOTNETAPPS\SHARPDEVELOP2\SRC\MAIN\BASE\PROJECT\SRC\EDITOR\CODECOMPLETION\CODECOMPLETIONPANELXAML.XAML'
19:03:19.986 [1] DEBUG - ActiveViewContentChanged to 
19:03:19.986 [1] DEBUG - ActiveContentChanged to [AvalonEditViewContent D:\B\DotNetApps\SharpDevelop2\src\AddIns\Debugger\Debugger.AddIn\Service\WindowsDebugger.cs]
19:03:19.999 [1] DEBUG - OpenedFileClosed: D:\B\DotNetApps\SharpDevelop2\src\Main\Base\Project\Src\Editor\CodeCompletion\CodeCompletionPanelXaml.xaml
19:03:19.999 [1] DEBUG - ActiveWorkbenchWindowChanged to [AvalonWorkbenchWindow: WindowsDebugger.cs]
19:03:19.999 [1] INFO - CurrentProject changed to Debugger.AddIn
19:03:20.000 [1] DEBUG - NavigationService
	ActiveViewContent: WindowsDebugger.cs
	          Subview: ${res:FormsDesigner.DesignTabPages.SourceTabPage}
19:03:20.000 [1] DEBUG - ActiveViewContentChanged to [AvalonEditViewContent D:\B\DotNetApps\SharpDevelop2\src\AddIns\Debugger\Debugger.AddIn\Service\WindowsDebugger.cs]
19:03:22.567 [1] DEBUG - ActiveContentChanged to ICSharpCode.SharpDevelop.Editor.Search.SearchResultsPad
19:03:23.911 [1] DEBUG - Creating text for search result (60, 4) 
19:03:24.119 [1] INFO - FileService
	Jumping to File Position:  [D:\B\DotNetApps\SharpDevelop2\src\Main\Base\Project\Src\Editor\Dialogs\RenameSymbolDialog.xaml : 60x4]
19:03:24.119 [1] DEBUG - NavigationService -- suspend logging
19:03:24.119 [1] INFO - Open file D:\B\DotNetApps\SharpDevelop2\src\Main\Base\Project\Src\Editor\Dialogs\RenameSymbolDialog.xaml
19:03:24.123 [1] DEBUG - TypeResolutionService: AssemblyResolveEventHandler: ICSharpCode.TreeView.resources, Version=5.0.0.4270, Culture=en, PublicKeyToken=f829da5c02be14ee
19:03:24.123 [1] DEBUG - TypeResolutionService: AssemblyResolveEventHandler: ICSharpCode.TreeView.resources, Version=5.0.0.4270, Culture=en, PublicKeyToken=f829da5c02be14ee
19:03:24.125 [1] DEBUG - OpenedFileClosed: D:\B\DotNetApps\SharpDevelop2\src\Main\Base\Project\Src\Editor\Dialogs\RenameSymbolDialog.xaml
19:03:24.125 [1] DEBUG - OpenedFileClosed: D:\B\DotNetApps\SharpDevelop2\src\Main\Base\Project\Src\Editor\Dialogs\RenameSymbolDialog.xaml
19:03:24.125 [1] INFO - FileService
	Jumped to File Position:  [D:\B\DotNetApps\SharpDevelop2\src\Main\Base\Project\Src\Editor\Dialogs\RenameSymbolDialog.xaml : 60x4]
19:03:24.125 [1] DEBUG - NavigationService -- resume logging
19:03:24.125 [1] ERROR - Unhandled WPF exception
--> Exception:
System.Windows.Markup.XamlParseException: Set connectionId threw an exception. ---> System.InvalidCastException: [A]ICSharpCode.TreeView.SharpTreeView cannot be cast to [B]ICSharpCode.TreeView.SharpTreeView. Type A originates from 'ICSharpCode.TreeView, Version=5.0.0.4270, Culture=neutral, PublicKeyToken=f829da5c02be14ee' in the context 'LoadNeither' in a byte array. Type B originates from 'ICSharpCode.TreeView, Version=5.0.0.4270, Culture=neutral, PublicKeyToken=f829da5c02be14ee' in the context 'Default' at location 'D:\B\DotNetApps\SharpDevelop\bin\ICSharpCode.TreeView.dll'.
   at ICSharpCode.XamlBinding.XamlOutlineContentHost.System.Windows.Markup.IComponentConnector.Connect(Int32 connectionId, Object target)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetConnectionId(Object root, Int32 connectionId, Object instance)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at ICSharpCode.XamlBinding.XamlOutlineContentHost.InitializeComponent()
   at ICSharpCode.XamlBinding.XamlOutlineContentHost..ctor(ITextEditor editor)
   at ICSharpCode.XamlBinding.XamlTextEditorExtension.Attach(ITextEditor editor)
   at ICSharpCode.AvalonEdit.AddIn.CodeEditorAdapter.AttachExtensions()
   at ICSharpCode.AvalonEdit.AddIn.CodeEditorAdapter.FileNameChanged()
   at ICSharpCode.AvalonEdit.AddIn.CodeEditor.set_FileName(FileName value)
   at ICSharpCode.AvalonEdit.AddIn.AvalonEditViewContent.Load(OpenedFile file, Stream stream)
   at ICSharpCode.SharpDevelop.Workbench.OpenedFile.SwitchedToView(IViewContent newView) in d:\B\DotNetApps\SharpDevelop\src\Main\Base\Project\Workbench\File\OpenedFile.cs:line 319
   at ICSharpCode.SharpDevelop.Workbench.OpenedFile.ForceInitializeView(IViewContent view) in d:\B\DotNetApps\SharpDevelop\src\Main\Base\Project\Workbench\File\OpenedFile.cs:line 146
   at ICSharpCode.SharpDevelop.Workbench.FileServiceOpenedFile.ForceInitializeView(IViewContent view)
   at ICSharpCode.AvalonEdit.AddIn.AvalonEditViewContent..ctor(OpenedFile file, Encoding fixedEncodingForLoading)
   at ICSharpCode.AvalonEdit.AddIn.AvalonEditDisplayBinding.CreateContentForFile(OpenedFile file)
   at ICSharpCode.SharpDevelop.Workbench.FileService.LoadFileWrapper.Invoke(FileName fileName)
   at ICSharpCode.Core.FileUtility.<>c__DisplayClass13.<ObservedLoad>b__12() in d:\B\DotNetApps\SharpDevelop\src\Main\Core\Project\Src\Services\FileUtility\FileUtility.cs:line 724
   at ICSharpCode.Core.FileUtility.ObservedLoad(FileOperationDelegate loadFile, FileName fileName, String message, FileErrorPolicy policy) in d:\B\DotNetApps\SharpDevelop\src\Main\Core\Project\Src\Services\FileUtility\FileUtility.cs:line 683
   at ICSharpCode.Core.FileUtility.ObservedLoad(NamedFileOperationDelegate saveFileAs, FileName fileName, String message, FileErrorPolicy policy) in d:\B\DotNetApps\SharpDevelop\src\Main\Core\Project\Src\Services\FileUtility\FileUtility.cs:line 724
   at ICSharpCode.Core.FileUtility.ObservedLoad(NamedFileOperationDelegate saveFileAs, FileName fileName, FileErrorPolicy policy) in d:\B\DotNetApps\SharpDevelop\src\Main\Core\Project\Src\Services\FileUtility\FileUtility.cs:line 729
   at ICSharpCode.SharpDevelop.Workbench.FileService.OpenFile(FileName fileName, Boolean switchToOpenedView)
   at ICSharpCode.SharpDevelop.Workbench.FileService.JumpToFilePosition(FileName fileName, Int32 line, Int32 column)
   at SearchAndReplace.SearchResultNode.ActivateItem()
   at SearchAndReplace.ResultsTreeView.OnMouseDoubleClick(MouseButtonEventArgs e)
   at System.Windows.Controls.Control.HandleDoubleClick(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

---- Post-error application state information:
Installed 3rd party AddIns: 
ProjectService.CurrentSolution: [Solution D:\B\DotNetApps\SharpDevelop2\SharpDevelop.sln with 76 projects]
ProjectService.CurrentProject: [CSharpProject: Debugger.AddIn]
Workbench.ActiveContent: ICSharpCode.SharpDevelop.Editor.Search.SearchResultsPad

**Comment by gumme** [comment]
I tried to trigger the crash in latest SD master without success. Can you add a step-by-step on how to reproduce the error?

**Comment by dgrunwald** [comment]
As with #292, this issue only occurs when using one of SharpDevelop's libraries (in this case, SharpTreeView) as a user control in the .xaml file being designed.
It also depends on the load order -- if the search results pad is loaded before the designer, everything is fine.
A proper fix for this issue would require running the designer in a separate AppDomain. However, I think it's also possible to work around the problem by preventing the load of SharpDevelop's assemblies into the designer, and instead make the designer use the normal copies already loaded in SharpDevelop (this workaround breaks down if the versions of the assembly differ, though I'm not sure if the problem even exists in that case).

**Comment by jogibear9988** [comment]
Or it could be fixed like I did it in the Designer Dlls, with the special ResourceDictionary, and the Special IntializeComponents call in UssrContrs!
