### ISSUE TITLE
Moving an ellipse inside a content control caused an unhandled exception

### ISSUE THREAD

**Issue by Rpinski** [icsharpcode/SharpDevelop#646]
Reported in forum: http://community.sharpdevelop.net/forums/t/22030.aspx

```
SharpDevelop Version : 5.1.0.4936-Beta-3ea20cfa
.NET Version         : 4.5.50938
OS Version           : Microsoft Windows NT 6.1.7601 Service Pack 1
Current culture      : Invariant Language (Invariant Country) ()
Current UI language  : en
Working Set Memory   : 210132kb
GC Heap Memory       : 78515kb

Unhandled WPF exception
Exception thrown:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetStream(String name, CultureInfo culture)
   at ICSharpCode.WpfDesign.Designer.Controls.ZoomControl.GetCursor(String path)
   at ICSharpCode.WpfDesign.Designer.Extensions.RotateThumbExtension.CreateRotateThumb()
   at ICSharpCode.WpfDesign.Designer.Extensions.RotateThumbExtension..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at ICSharpCode.WpfDesign.Extensions.DefaultExtensionServer.CreateExtension(Type extensionType, DesignItem extendedItem)
   at ICSharpCode.WpfDesign.Extensions.ExtensionManager.<CreateExtensions>d__e.MoveNext()
   at ICSharpCode.WpfDesign.DesignItem.ApplyUnapplyExtensionServer(ExtensionManager extensionManager, Boolean shouldApply, ExtensionServer server)
   at ICSharpCode.WpfDesign.DesignItem.ReapplyExtensionServer(ExtensionManager extensionManager, ExtensionServer server)
   at ICSharpCode.WpfDesign.Extensions.ExtensionManager.ReapplyExtensions(IEnumerable`1 items, ExtensionServer server)
   at ICSharpCode.WpfDesign.Extensions.ExtensionManager.<GetExtensionServer>b__15(Object sender, DesignItemCollectionEventArgs e)
   at ICSharpCode.WpfDesign.Extensions.DefaultExtensionServer.ReapplyExtensions(ICollection`1 items)
   at ICSharpCode.WpfDesign.Extensions.PrimarySelectionExtensionServer.OnPrimarySelectionChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at ICSharpCode.WpfDesign.Designer.Services.DefaultSelectionService.SetSelectedComponents(ICollection`1 components, SelectionTypes selectionType)
   at ICSharpCode.WpfDesign.Designer.Services.DefaultSelectionService.SetSelectedComponents(ICollection`1 components)
   at ICSharpCode.WpfDesign.Designer.Extensions.DefaultPlacementBehavior.EndPlacement(PlacementOperation operation)
   at ICSharpCode.WpfDesign.Designer.Extensions.StackPanelPlacementSupport.EndPlacement(PlacementOperation operation)
   at ICSharpCode.WpfDesign.PlacementOperation.Commit()
   at ICSharpCode.WpfDesign.Designer.Services.MoveLogic.Stop()
   at ICSharpCode.WpfDesign.Designer.Services.DragMoveMouseGesture.OnMouseUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by jogibear9988** [comment]
I'll tried, and could not reproduce it! (But I used my fork wich includes my Pull req, but I don't think I've change many in this direction)

Is it possible to post XAML wich Produces this error?

**Comment by gumme** [comment]
I could not reproduce it in latest SD master.

I analyzed the code based on the provided call stack but could not find any obvious errors.

**Comment by jogibear9988** [comment]
I think this also should be closed!
