### ISSUE TITLE
Running unit tests with the profiler throws an exception

### ISSUE THREAD

**Issue by Dasaan** [icsharpcode/SharpDevelop#684]
SharpDevelop Version : 5.1.0.5108-Beta 2-85810a07
.NET Version         : 4.5.51209
OS Version           : Microsoft Windows NT 6.1.7601 Service Pack 1
Current culture      : English (United Kingdom) (en-GB)
Running under WOW6432, processor architecture: x86-64
Working Set Memory   : 183500kb
GC Heap Memory       : 48565kb

Unhandled WPF exception
Exception thrown:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Profiler.AddIn.Commands.RunSelectedTestsWithProfilerCommand.Run()
   at ICSharpCode.Core.AbstractMenuCommand.System.Windows.Input.ICommand.Execute(Object parameter)
   at ICSharpCode.Core.CommandWrapper.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

---- Recent log messages:
21:26:15.797 [1] DEBUG - CompilerMessageView: Combined 5 appends.
21:26:15.802 [1] DEBUG - CompilerMessageView: Combined 4 appends.
21:26:15.806 [1] DEBUG - CompilerMessageView: Combined 2 appends.
21:26:15.820 [UnitTesting Pipe Reader] DEBUG - End of pipe
21:26:15.826 [1] DEBUG - CompilerMessageView: Combined 2 appends.
21:26:15.841 [8] DEBUG - Waiting for pipe reader to finish
21:26:15.841 [8] DEBUG - Pipe reader has finished
21:26:15.842 [1] DEBUG - Creating pad ICSharpCode.SharpDevelop.Gui.ErrorListPad...
21:26:15.914 [1] DEBUG - ActiveContentChanged to 
21:26:20.374 [1] DEBUG - ActiveContentChanged to ICSharpCode.UnitTesting.UnitTestsPad
21:26:21.269 [22] DEBUG - Telling worker process to exit
21:26:21.269 [22] DEBUG - Waiting for thread-join
21:26:21.271 [17] DEBUG - Cannot read from WorkerProcess 5252: end of stream
21:26:21.271 [17] DEBUG - Stopped reading from WorkerProcess 5252.
21:26:21.271 [17] DEBUG - Telling worker process to exit
21:26:21.271 [17] DEBUG - End of reader thread on WorkerProcess 5252.
21:26:21.271 [22] DEBUG - Joined!
21:26:21.472 [21] DEBUG - Telling worker process to exit
21:26:21.472 [21] DEBUG - Waiting for thread-join
21:26:21.474 [10] DEBUG - Cannot read from WorkerProcess 4200: end of stream
21:26:21.474 [10] DEBUG - Stopped reading from WorkerProcess 4200.
21:26:21.474 [10] DEBUG - Telling worker process to exit
21:26:21.474 [10] DEBUG - End of reader thread on WorkerProcess 4200.
21:26:21.474 [21] DEBUG - Joined!
21:26:22.102 [1] ERROR - Unhandled WPF exception
--> Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Profiler.AddIn.Commands.RunSelectedTestsWithProfilerCommand.Run()
   at ICSharpCode.Core.AbstractMenuCommand.System.Windows.Input.ICommand.Execute(Object parameter)
   at ICSharpCode.Core.CommandWrapper.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

---- Post-error application state information:
Installed 3rd party AddIns: 
ProjectService.CurrentSolution: [Solution C:\Users\Grahame\Documents\SharpDevelop Projects\SimSysII\SimSys2_WithUnitTests.sln with 8 projects]
ProjectService.CurrentProject: [CSharpProject: SimSys2]
Workbench.ActiveContent: ICSharpCode.UnitTesting.UnitTestsPad

**Comment by timajc** [comment]
I also have the same issue.  Trying to run the profiler on an Nunit test.  Have tried with multiple unit tests from complex to simple - always comes back with same error "ICSharpCode.Profiler.Controller.ProfilerException: File is not a valid .NET executable file!".

SharpDevelop Version : 5.1.0.5216-0e58df71
.NET Version         : 4.7.02046
OS Version           : Microsoft Windows NT 6.3.9600.0
Current culture      : English (United States) (en-US)
Running under WOW6432, processor architecture: x86-64
Working Set Memory   : 286768kb
GC Heap Memory       : 132918kb

Exception thrown:
ICSharpCode.Profiler.Controller.ProfilerException: File is not a valid .NET executable file!
   at ICSharpCode.Profiler.Controller.Profiler..ctor(ProcessStartInfo info, IProfilingDataWriter dataWriter, ProfilerOptions options)
   at ICSharpCode.Profiler.AddIn.ProfilerRunner..ctor(ProcessStartInfo startInfo, Boolean useTempFileDatabase, IProfilingDataWriter writer)
   at ICSharpCode.Profiler.AddIn.ProfilerProcessRunner.Start(String program, String[] arguments)
   at ICSharpCode.Profiler.AddIn.ProfilerProcessRunner.StartCommandLine(String commandLine)
   at ICSharpCode.UnitTesting.TestProcessRunnerBase.Start(ProcessStartInfo processStartInfo)
   at ICSharpCode.UnitTesting.TestProcessRunnerBase.Start(IEnumerable`1 selectedTests)
   at ICSharpCode.UnitTesting.TestRunnerBase.RunAsync(IEnumerable`1 selectedTests, IProgress`1 progress, TextWriter output, CancellationToken cancellationToken)
   at ICSharpCode.UnitTesting.Frameworks.TestExecutionManager.<RunTestsAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ICSharpCode.UnitTesting.SDTestService.<RunTestsAsync>d__15.MoveNext()

---- Recent log messages:
16:58:04.056 [15] DEBUG - Setting property SolutionName to 'TEMP'
16:58:04.056 [15] DEBUG - Setting property SolutionPath to 'C:\MyDocsLocal\Software\c#\TEMP\TEMP.sln'
16:58:04.061 [28] DEBUG - Received command ReportEvent
16:58:04.100 [28] DEBUG - Received command ReportEvent
16:58:04.100 [28] DEBUG - Received command ReportEvent
16:58:04.115 [28] DEBUG - Received command ReportEvent
16:58:04.115 [28] DEBUG - Received command ReportEvent
16:58:04.131 [28] DEBUG - Received command ReportEvent
16:58:04.131 [28] DEBUG - Received command ReportEvent
16:58:04.131 [28] DEBUG - Received command ReportEvent
16:58:04.131 [28] DEBUG - Received command ReportEvent
16:58:04.131 [28] DEBUG - Received command ReportEvent
16:58:04.131 [28] DEBUG - Received command ReportEvent
16:58:04.334 [28] DEBUG - Received command ReportEvent
16:58:04.350 [28] DEBUG - Received command ReportEvent
16:58:04.350 [28] DEBUG - Received command ReportEvent
16:58:04.350 [28] DEBUG - Received command ReportEvent
16:58:04.350 [28] DEBUG - Received command ReportEvent
16:58:04.350 [28] DEBUG - Received command ReportEvent
16:58:04.350 [28] DEBUG - Received command BuildDone
16:58:04.350 [28] INFO - Finished building MathRF, success=True
16:58:04.350 [1] DEBUG - ActiveContentChanged to ICSharpCode.SharpDevelop.Gui.ErrorListPad
16:58:04.365 [UnitTesting Pipe Reader] DEBUG - Waiting for connection to pipe
16:58:04.365 [7] ERROR - 
--> Exception:
ICSharpCode.Profiler.Controller.ProfilerException: File is not a valid .NET executable file!
   at ICSharpCode.Profiler.Controller.Profiler..ctor(ProcessStartInfo info, IProfilingDataWriter dataWriter, ProfilerOptions options)
   at ICSharpCode.Profiler.AddIn.ProfilerRunner..ctor(ProcessStartInfo startInfo, Boolean useTempFileDatabase, IProfilingDataWriter writer)
   at ICSharpCode.Profiler.AddIn.ProfilerProcessRunner.Start(String program, String[] arguments)
   at ICSharpCode.Profiler.AddIn.ProfilerProcessRunner.StartCommandLine(String commandLine)
   at ICSharpCode.UnitTesting.TestProcessRunnerBase.Start(ProcessStartInfo processStartInfo)
   at ICSharpCode.UnitTesting.TestProcessRunnerBase.Start(IEnumerable`1 selectedTests)
   at ICSharpCode.UnitTesting.TestRunnerBase.RunAsync(IEnumerable`1 selectedTests, IProgress`1 progress, TextWriter output, CancellationToken cancellationToken)
   at ICSharpCode.UnitTesting.Frameworks.TestExecutionManager.<RunTestsAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ICSharpCode.UnitTesting.SDTestService.<RunTestsAsync>d__15.MoveNext()
16:58:04.381 [7] WARN - Stack trace of last exception log:
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at ICSharpCode.SharpDevelop.Logging.SDMessageService.ShowException(Exception ex, String message)
   at ICSharpCode.SharpDevelop.SharpDevelopExtensions.<>c.<FireAndForget>b__2_0(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

---- Post-error application state information:
Installed 3rd party AddIns: 
ProjectService.CurrentSolution: [Solution C:\MyDocsLocal\Software\c#\TEMP\TEMP.sln with 5 projects]
ProjectService.CurrentProject: [CSharpProject: MathRF]
Workbench.ActiveContent: System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at ICSharpCode.SharpDevelop.DispatcherMessageLoop.VerifyAccess()
   at ICSharpCode.SharpDevelop.Workbench.WpfWorkbench.get_ActiveContent()
   at ICSharpCode.SharpDevelop.Workbench.WorkbenchStartup.<>c.<InitializeWorkbench>b__4_0()
   at ICSharpCode.Core.ApplicationStateInfoService.GetCurrentApplicationStateInfo()
