### ISSUE TITLE
How to add an image in a Report ?

### ISSUE THREAD

**Issue by giuliohome** [icsharpcode/SharpDevelop#687]
I'm getting the exception "Value cannot be null.\r\nParameter name: path1"
The code is:
```c#
			try {
				ReportEngine engine = new ReportEngine();
				ReportParameters pm = new ReportParameters();
				string reportPath= "Report1.srd";
				ReportModel reportModel = ReportEngine.LoadReportModel(reportPath);
				IReportCreator builder = FormPageBuilder.CreateInstance(reportModel); //ReportEngine.CreatePageBuilder(reportPath, null);
				builder.BuildExportList();
				PdfRenderer pdfRenderer = PdfRenderer.CreateInstance( builder, "TestThis.pdf", false);
				pdfRenderer.Start();
				pdfRenderer.RenderOutput();
				pdfRenderer.End();
				tx_status.Text="Printed";
			} catch (Exception exc) {
				tx_status.Text = exc.Message;
			}
```
and the srd contains something like the following node:

```xml
                    <Items>
                        <BaseImageItem>
                            <Location>428, 570</Location>
                            <Size>242, 160</Size>
                            <BackColor>White</BackColor>
                            <ImageFileName>C:\Dati\sharpdevelop projects\reports\direct_pdf\print\Img\MyImageName.jpg</ImageFileName>
                            <ScaleImageToSize>False</ScaleImageToSize>
                            <ImageSource>File</ImageSource>
                            <RelativeFileName>..\Img\MyImageName.jpg</RelativeFileName>
                        </BaseImageItem>
                    </Items>
```

Version info:
SharpDevelop Version : 4.4.2.9749-39bf891c
.NET Version         : 4.0.30319.2045

Please help me, thank you!

--- *** ---
Stack trace
```c#
   at System.IO.Path.Combine(String path1, String path2)
   at ICSharpCode.Reports.Core.BaseImageItem.get_AbsoluteFileName()
   at ICSharpCode.Reports.Core.BaseImageItem.LoadImage()
   at ICSharpCode.Reports.Core.BaseImageItem.get_Image()
   at ICSharpCode.Reports.Core.BaseImageItem.CreateExportColumn()
   at ICSharpCode.Reports.Core.Exporter.ExportHelper.ConvertLineItem(BaseReportItem item, Point offset)
   at ICSharpCode.Reports.Core.Exporter.ExportHelper.ConvertPlainCollection(ReportItemCollection items, Point offset)
   at ICSharpCode.Reports.Core.Exporter.BaseConverter.ConvertItems(ISimpleContainer row, Point offset)
   at ICSharpCode.Reports.Core.Exporter.BaseConverter.ConvertContainer(ExporterCollection myList, ISimpleContainer container, Int32 leftPos, Point curPos)
   at ICSharpCode.Reports.Core.Exporter.BasePager.ConvertSection(BaseSection section, Int32 dataRow)
   at ICSharpCode.Reports.Core.Exporter.FormPageBuilder.BuildDetailInternal(BaseSection section)
   at ICSharpCode.Reports.Core.Exporter.FormPageBuilder.BuildNewPage()
   at ICSharpCode.Reports.Core.Exporter.FormPageBuilder.WritePages()
   at ICSharpCode.Reports.Core.Exporter.FormPageBuilder.BuildExportList()
   at print.Window1.button1_Click(Object sender, RoutedEventArgs e) in c:\Dati\sharpdevelop projects\reports\direct_pdf\print\Window1.xaml.cs:line 44
```

**Comment by giuliohome** [comment]
Fixed by myself: I've manually deleted the whole below line from the srd with a notepad++
```xml
<RelativeFileName>..\Img\MyImageName.jpg</RelativeFileName>
```

**Comment by giuliohome** [comment]
IMPORTANT: the issue happens when the image is include in a rectangle

**Comment by giuliohome** [comment]
I've ported the code to SD 5 beta 2:
```c#
		Stream LoadPlainResource()
		{
			Assembly asm = Assembly.GetExecutingAssembly();
			var stream = asm.GetManifestResourceStream("PdfReport.Report1.srd");
			return stream;
		}
```

```c#
			var rf = new ReportingFactory();
			var reportCreator = rf.ReportCreator(stream);
			reportCreator.BuildExportList();		
			var previewViewModel = new PreviewViewModel (rf.ReportModel.ReportSettings,reportCreator.Pages);
			viewer.SetBinding(previewViewModel);
```

working srd with 2 separate rectangles and not working one with one insede the other

```xml
<?xml version="1.0" encoding="utf-8"?>
<ReportModel>
    <ReportSettings>
        <ReportSettings>
            <ReportName>BioModel</ReportName>
            <DataModel>FormSheet</DataModel>
            <BottomMargin>50</BottomMargin>
            <TopMargin>50</TopMargin>
            <LeftMargin>50</LeftMargin>
            <RightMargin>50</RightMargin>
            <Landscape>False</Landscape>
            <ParameterCollection />
            <SortColumnsCollection />
            <GroupColumnsCollection />
        </ReportSettings>
    </ReportSettings>
    <SectionCollection>
        <BaseSection>
            <Location>50, 50</Location>
            <Size>727, 70</Size>
            <BackColor>White</BackColor>
            <DrawBorder>False</DrawBorder>
            <Items>
                <BaseTextItem>
                    <Location>313, 10</Location>
                    <Size>100, 20</Size>
                    <BackColor>White</BackColor>
                    <Font>Microsoft Sans Serif, 10pt</Font>
                    <StringTrimming>None</StringTrimming>
                    <ContentAlignment>TopLeft</ContentAlignment>
                    <TextAlignment>Left</TextAlignment>
                    <CanGrow>False</CanGrow>
                    <CanShrink>False</CanShrink>
                    <DataType>System.String</DataType>
                    <Text>BioModel</Text>
                    <DrawBorder>False</DrawBorder>
                    <FrameColor>Black</FrameColor>
                    <ForeColor>Black</ForeColor>
                    <Name>BaseTextItem</Name>
                </BaseTextItem>
                <BaseTextItem>
                    <Location>622, 10</Location>
                    <Size>100, 20</Size>
                    <BackColor>White</BackColor>
                    <Font>Microsoft Sans Serif, 10pt</Font>
                    <StringTrimming>None</StringTrimming>
                    <ContentAlignment>TopLeft</ContentAlignment>
                    <TextAlignment>Left</TextAlignment>
                    <CanGrow>False</CanGrow>
                    <CanShrink>False</CanShrink>
                    <DataType>System.String</DataType>
                    <Text>= Today.Today</Text>
                    <DrawBorder>False</DrawBorder>
                    <FrameColor>Black</FrameColor>
                    <ForeColor>Black</ForeColor>
                    <Name>BaseTextItem</Name>
                </BaseTextItem>
            </Items>
            <FrameColor>Black</FrameColor>
            <Name>ReportHeader</Name>
        </BaseSection>
        <BaseSection>
            <Location>50, 135</Location>
            <Size>727, 70</Size>
            <BackColor>White</BackColor>
            <DrawBorder>False</DrawBorder>
            <Items />
            <FrameColor>Black</FrameColor>
            <Name>ReportPageHeader</Name>
        </BaseSection>
        <BaseSection>
            <Location>50, 220</Location>
            <Size>727, 403</Size>
            <BackColor>White</BackColor>
            <DrawBorder>False</DrawBorder>
            <Items>
                <BaseRectangleItem>
                    <Location>285, 232</Location>
                    <Size>75, 23</Size>
                    <BackColor>Aquamarine</BackColor>
                    <ForeColor>Black</ForeColor>
                    <DashStyle>Solid</DashStyle>
                    <Thickness>1</Thickness>
                    <CornerRadius>1</CornerRadius>
                    <Items />
                    <Name>BaseRectangleItem2</Name>
                </BaseRectangleItem>
                <BaseRectangleItem>
                    <Location>58, 218</Location>
                    <Size>179, 143</Size>
                    <BackColor>DarkKhaki</BackColor>
                    <ForeColor>Black</ForeColor>
                    <DashStyle>Solid</DashStyle>
                    <Thickness>1</Thickness>
                    <CornerRadius>1</CornerRadius>
                    <Items />
                    <Name>BaseRectangleItem1</Name>
                </BaseRectangleItem>
            </Items>
            <FrameColor>Black</FrameColor>
            <Name>ReportDetail</Name>
        </BaseSection>
        <BaseSection>
            <Location>50, 638</Location>
            <Size>727, 70</Size>
            <BackColor>White</BackColor>
            <DrawBorder>False</DrawBorder>
            <Items />
            <FrameColor>Black</FrameColor>
            <Name>ReportPageFooter</Name>
        </BaseSection>
        <BaseSection>
            <Location>50, 723</Location>
            <Size>727, 70</Size>
            <BackColor>White</BackColor>
            <DrawBorder>False</DrawBorder>
            <Items />
            <FrameColor>Black</FrameColor>
            <Name>ReportFooter</Name>
        </BaseSection>
    </SectionCollection>
</ReportModel>
```
not working srd below:
```xml
<?xml version="1.0" encoding="utf-8"?>
<ReportModel>
    <ReportSettings>
        <ReportSettings>
            <ReportName>BioModel</ReportName>
            <DataModel>FormSheet</DataModel>
            <BottomMargin>50</BottomMargin>
            <TopMargin>50</TopMargin>
            <LeftMargin>50</LeftMargin>
            <RightMargin>50</RightMargin>
            <Landscape>False</Landscape>
            <ParameterCollection />
            <SortColumnsCollection />
            <GroupColumnsCollection />
        </ReportSettings>
    </ReportSettings>
    <SectionCollection>
        <BaseSection>
            <Location>50, 50</Location>
            <Size>727, 70</Size>
            <BackColor>White</BackColor>
            <DrawBorder>False</DrawBorder>
            <Items>
                <BaseTextItem>
                    <Location>313, 10</Location>
                    <Size>100, 20</Size>
                    <BackColor>White</BackColor>
                    <Font>Microsoft Sans Serif, 10pt</Font>
                    <StringTrimming>None</StringTrimming>
                    <ContentAlignment>TopLeft</ContentAlignment>
                    <TextAlignment>Left</TextAlignment>
                    <CanGrow>False</CanGrow>
                    <CanShrink>False</CanShrink>
                    <DataType>System.String</DataType>
                    <Text>BioModel</Text>
                    <DrawBorder>False</DrawBorder>
                    <FrameColor>Black</FrameColor>
                    <ForeColor>Black</ForeColor>
                    <Name>BaseTextItem</Name>
                </BaseTextItem>
                <BaseTextItem>
                    <Location>622, 10</Location>
                    <Size>100, 20</Size>
                    <BackColor>White</BackColor>
                    <Font>Microsoft Sans Serif, 10pt</Font>
                    <StringTrimming>None</StringTrimming>
                    <ContentAlignment>TopLeft</ContentAlignment>
                    <TextAlignment>Left</TextAlignment>
                    <CanGrow>False</CanGrow>
                    <CanShrink>False</CanShrink>
                    <DataType>System.String</DataType>
                    <Text>= Today.Today</Text>
                    <DrawBorder>False</DrawBorder>
                    <FrameColor>Black</FrameColor>
                    <ForeColor>Black</ForeColor>
                    <Name>BaseTextItem</Name>
                </BaseTextItem>
            </Items>
            <FrameColor>Black</FrameColor>
            <Name>ReportHeader</Name>
        </BaseSection>
        <BaseSection>
            <Location>50, 135</Location>
            <Size>727, 70</Size>
            <BackColor>White</BackColor>
            <DrawBorder>False</DrawBorder>
            <Items />
            <FrameColor>Black</FrameColor>
            <Name>ReportPageHeader</Name>
        </BaseSection>
        <BaseSection>
            <Location>50, 220</Location>
            <Size>727, 403</Size>
            <BackColor>White</BackColor>
            <DrawBorder>False</DrawBorder>
            <Items>
                <BaseRectangleItem>
                    <Location>58, 218</Location>
                    <Size>179, 143</Size>
                    <BackColor>DarkKhaki</BackColor>
                    <ForeColor>Black</ForeColor>
                    <DashStyle>Solid</DashStyle>
                    <Thickness>1</Thickness>
                    <CornerRadius>1</CornerRadius>
                    <Items>
                        <BaseRectangleItem>
                            <Location>64, 42</Location>
                            <Size>75, 23</Size>
                            <BackColor>Aquamarine</BackColor>
                            <ForeColor>Black</ForeColor>
                            <DashStyle>Solid</DashStyle>
                            <Thickness>1</Thickness>
                            <CornerRadius>1</CornerRadius>
                            <Items />
                            <Name>BaseRectangleItem2</Name>
                        </BaseRectangleItem>
                    </Items>
                    <Name>BaseRectangleItem1</Name>
                </BaseRectangleItem>
            </Items>
            <FrameColor>Black</FrameColor>
            <Name>ReportDetail</Name>
        </BaseSection>
        <BaseSection>
            <Location>50, 638</Location>
            <Size>727, 70</Size>
            <BackColor>White</BackColor>
            <DrawBorder>False</DrawBorder>
            <Items />
            <FrameColor>Black</FrameColor>
            <Name>ReportPageFooter</Name>
        </BaseSection>
        <BaseSection>
            <Location>50, 723</Location>
            <Size>727, 70</Size>
            <BackColor>White</BackColor>
            <DrawBorder>False</DrawBorder>
            <Items />
            <FrameColor>Black</FrameColor>
            <Name>ReportFooter</Name>
        </BaseSection>
    </SectionCollection>
</ReportModel>
```

Stack Trace:
```c#
System.InvalidOperationException: L'elemento specificato è già il figlio logico di un altro elemento. È innanzitutto necessario disconnetterlo.

   in System.Windows.FrameworkElement.ChangeLogicalParent(DependencyObject newParent)
   in MS.Internal.FrameworkObject.ChangeLogicalParent(DependencyObject newParent)
   in System.Windows.FrameworkElement.AddLogicalChild(Object child)
   in System.Windows.Controls.UIElementCollection.SetLogicalParent(UIElement element)
   in System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   in System.Windows.Controls.UIElementCollection.Add(UIElement element)
   in ICSharpCode.Reporting.WpfReportViewer.Visitor.WpfVisitor.CreateItemsInContainer(List`1 items)
   in ICSharpCode.Reporting.WpfReportViewer.Visitor.WpfVisitor.Visit(ExportRectangle exportRectangle)
   in ICSharpCode.Reporting.WpfReportViewer.Visitor.WpfVisitor.RenderGraphicsContainer(IExportColumn column)
   in ICSharpCode.Reporting.WpfReportViewer.Visitor.WpfVisitor.RenderRow(Canvas canvas, IExportContainer container)
   in ICSharpCode.Reporting.WpfReportViewer.Visitor.WpfVisitor.RenderSectionContainer(ExportContainer container)
   in ICSharpCode.Reporting.WpfReportViewer.Visitor.WpfVisitor.Visit(ExportContainer exportContainer)
   in ICSharpCode.Reporting.PageBuilder.ExportColumns.ExportContainer.Accept(IVisitor visitor)
   in ICSharpCode.Reporting.WpfReportViewer.Visitor.WpfVisitor.Visit(ExportPage page)
   in ICSharpCode.Reporting.WpfReportViewer.Visitor.WpfExporter.Run()
   in ICSharpCode.Reporting.WpfReportViewer.PreviewViewModel..ctor(ReportSettings reportSettings, Collection`1 pages)
   in PdfReport.Window1.button1_Click(Object sender, RoutedEventArgs e) in c:\SharpDevelop Projects\5xx\TestReport\PdfReport\PdfReport\Window1.xaml.cs:riga 49
   in System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   in System.Windows.RouteItem.InvokeHandler(RoutedEventArgs routedEventArgs)
   in System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   in System.Windows.EventRoute.InvokeHandlers(Object source, RoutedEventArgs args)
   in System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   in System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   in System.Windows.Controls.Primitives.ButtonBase.OnClick()
   in System.Windows.Controls.Button.OnClick()
   in System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   in System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   in System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   in System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   in System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   in System.Windows.RouteItem.InvokeHandler(RoutedEventArgs routedEventArgs)
   in System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   in System.Windows.EventRoute.ReInvokeHandlers(Object source, RoutedEventArgs args)
   in System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   in System.Windows.UIElement.CrackMouseButtonEventAndReRaiseEvent(DependencyObject sender, MouseButtonEventArgs e)
   in System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   in System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   in System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   in System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   in System.Windows.RouteItem.InvokeHandler(RoutedEventArgs routedEventArgs)
   in System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   in System.Windows.EventRoute.InvokeHandlers(Object source, RoutedEventArgs args)
   in System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   in System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   in System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   in System.Windows.Input.InputManager.ProcessStagingArea()
   in System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   in System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   in System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   in System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   in System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   in MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   in MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   in System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   in System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   in System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   in MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   in System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSG& msg)
   in System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   in System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   in System.Windows.Threading.Dispatcher.Run()
   in System.Windows.Application.RunDispatcher(Object ignore)
   in System.Windows.Application.RunInternal(Window window)
   in System.Windows.Application.Run(Window window)
   in System.Windows.Application.Run()
   in PdfReport.App.Main() in c:\SharpDevelop Projects\5xx\TestReport\PdfReport\PdfReport\obj\Debug\App.g.cs:riga 0
```

**Comment by giuliohome** [comment]
In the meantime I've found a little patch for #D 4

Ref to:

SharpDevelop_4.4.2.9749_Source\src\AddIns\Misc\Reports\ICSharpCode.Reports.Core\Project\Globals\FilePathConverter.cs

```c#
public static void AdjustReportName (ReportModel model)
		{
			if (model == null) {
				throw new ArgumentNullException("model");
			}
            System.Diagnostics.Debug.WriteLine("AdjustReportName");
			foreach (BaseSection section in model.SectionCollection) {
				foreach (BaseReportItem item in section.Items) {
                    System.Diagnostics.Debug.WriteLine(
                            "item: " + item.GetType()
                        );
                    BaseImageItem baseImageItem = item as BaseImageItem;
					if (baseImageItem != null) {
						baseImageItem.ReportFileName = model.ReportSettings.FileName;
					}
                    BaseRectangleItem baseRectangleItem = item as BaseRectangleItem;
                    if (baseRectangleItem != null)
                    {
                        foreach (BaseReportItem subitem in baseRectangleItem.Items)
                        {
                            System.Diagnostics.Debug.WriteLine(
                                "sub-item: " + subitem.GetType()
                            );
                            BaseImageItem subBaseImageItem = subitem as BaseImageItem;
                            if (subBaseImageItem != null)
                            {
                                subBaseImageItem.ReportFileName = model.ReportSettings.FileName;
                            }
                        }
                    }
				}
			}
		}
```
