### ISSUE TITLE
SharpDevelop crashed on mouse right-click

### ISSUE THREAD

**Issue by kjola** [icsharpcode/SharpDevelop#738]
I always get exc, while mouse right-click at code in SharpDevelop editor (see below).
However, my project builds and then application runs correctly.
I was working with SharpDevelop 5.0, - problem occurs (always)
under 5.1 - same.
---------------------------------------------------------------------------------------------------------
SharpDevelop Version : 5.1.0.5134-RC-d5052dc5
.NET Version         : 4.5.51209
OS Version           : Microsoft Windows NT 6.0.6002 Service Pack 2
Current culture      : Polish (Poland) (pl-PL)
Current UI language  : en
Working Set Memory   : 345976kb
GC Heap Memory       : 130300kb

Unhandled WPF exception
Exception thrown:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.UnitTesting.SDTestService.GetTestFrameworkForProject(IProject project)
   at ICSharpCode.UnitTesting.TestSolution.ProjectChangeListener.CheckTestFramework()
   at ICSharpCode.UnitTesting.TestSolution.ProjectChangeListener.Start()
   at ICSharpCode.UnitTesting.TestSolution.AddProject(IProject project)
   at ICSharpCode.UnitTesting.TestSolution..ctor(ITestService testService, IResourceService resourceService)
   at ICSharpCode.UnitTesting.SDTestService.get_OpenSolution()
   at ICSharpCode.UnitTesting.TestableCondition.IsValid(Object caller, Condition condition)
   at ICSharpCode.Core.Condition.IsValid(Object parameter)
   at ICSharpCode.Core.Condition.GetFailedAction(IEnumerable`1 conditionList, Object parameter)
   at ICSharpCode.Core.CommandWrapper.CanExecute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CanExecuteCommandSource(ICommandSource commandSource)
   at System.Windows.Controls.MenuItem.UpdateCanExecute()
   at System.Windows.Controls.MenuItem.OnCanExecuteChanged(Object sender, EventArgs e)
   at System.Windows.Input.CanExecuteChangedEventManager.HandlerSink.OnCanExecuteChanged(Object sender, EventArgs e)
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Listener& listener, Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Windows.Input.CommandManager.RequerySuggestedEventManager.OnRequerySuggested(Object sender, EventArgs args)
   at System.Windows.Input.CommandManager.RaiseRequerySuggested(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

---- Recent log messages:
12:05:23.751 [1] DEBUG - Resolved (Line 11, Col 2) to 
12:05:23.751 [1] DEBUG - Resolved (Line 11, Col 2) to 
12:05:23.751 [1] DEBUG - Resolved (Line 11, Col 2) to 
12:05:23.751 [1] DEBUG - Resolved (Line 11, Col 2) to 
12:05:24.154 [6] DEBUG - Resolved (Line 11, Col 2) to 
12:05:24.997 [1] DEBUG - Resolved (Line 11, Col 2) to 
12:05:24.998 [1] DEBUG - Resolved (Line 11, Col 2) to 
12:05:24.998 [1] DEBUG - Resolved (Line 11, Col 2) to 
12:05:24.998 [1] DEBUG - Resolved (Line 11, Col 2) to 
12:05:24.998 [1] DEBUG - Resolved (Line 11, Col 2) to 
12:16:57.587 [1] DEBUG - Resolved (Line 11, Col 2) to 
12:16:57.587 [1] DEBUG - Resolved (Line 11, Col 2) to 
12:16:57.587 [1] DEBUG - Resolved (Line 11, Col 2) to 
12:16:57.587 [1] DEBUG - Resolved (Line 11, Col 2) to 
12:16:57.587 [1] DEBUG - Resolved (Line 11, Col 2) to 
12:16:58.133 [1] DEBUG - Resolved (Line 24, Col 5) to [ResolveResult System.Void]
12:16:58.770 [1] DEBUG - Resolved (Line 18, Col 10) to 
12:17:04.977 [1] DEBUG - Resolved (Line 13, Col 20) to ***
12:17:04.977 [1] DEBUG - Resolved (Line 13, Col 20) to ***
12:17:04.977 [1] DEBUG - Resolved (Line 13, Col 20) to ***
12:17:04.977 [1] DEBUG - Resolved (Line 13, Col 20) to ***
12:17:04.977 [1] DEBUG - Resolved (Line 13, Col 20) to [TypeResolveResult ***]
12:17:04.978 [1] DEBUG - Resolved (Line 13, Col 20) to [TypeResolveResult ***]
12:17:04.978 [1] ERROR - Cannot find class: ICSharpCode.MSTest.MSTestFramework
12:17:04.979 [1] ERROR - Unhandled WPF exception
--> Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.UnitTesting.SDTestService.GetTestFrameworkForProject(IProject project)
   at ICSharpCode.UnitTesting.TestSolution.ProjectChangeListener.CheckTestFramework()
   at ICSharpCode.UnitTesting.TestSolution.ProjectChangeListener.Start()
   at ICSharpCode.UnitTesting.TestSolution.AddProject(IProject project)
   at ICSharpCode.UnitTesting.TestSolution..ctor(ITestService testService, IResourceService resourceService)
   at ICSharpCode.UnitTesting.SDTestService.get_OpenSolution()
   at ICSharpCode.UnitTesting.TestableCondition.IsValid(Object caller, Condition condition)
   at ICSharpCode.Core.Condition.IsValid(Object parameter)
   at ICSharpCode.Core.Condition.GetFailedAction(IEnumerable`1 conditionList, Object parameter)
   at ICSharpCode.Core.CommandWrapper.CanExecute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CanExecuteCommandSource(ICommandSource commandSource)
   at System.Windows.Controls.MenuItem.UpdateCanExecute()
   at System.Windows.Controls.MenuItem.OnCanExecuteChanged(Object sender, EventArgs e)
   at System.Windows.Input.CanExecuteChangedEventManager.HandlerSink.OnCanExecuteChanged(Object sender, EventArgs e)
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Listener& listener, Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Windows.Input.CommandManager.RequerySuggestedEventManager.OnRequerySuggested(Object sender, EventArgs args)
   at System.Windows.Input.CommandManager.RaiseRequerySuggested(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

---- Post-error application state information:
Installed 3rd party AddIns: [MSTest 0.0.0.0]
ProjectService.CurrentSolution: [Solution *** with 59 projects]
ProjectService.CurrentProject: [CSharpProject: ***]
Workbench.ActiveContent: [AvalonEditViewContent ***]
---------------------------------------------------------------------------------------------------------

**Comment by mrward** [comment]
Can you try disabling or removing the third party MSTest addin?

**Comment by kjola** [comment]
With MSTest disabled - this exc does not occur.

What can be the problem then?

**Comment by mrward** [comment]
The MSTest addin that is included as a sample in the SharpDevelop source code. I cannot reproduce the exception by right clicking in the text editor when that version of the MSTest addin is built and being used by SharpDevelop. So I can only guess that you have an old incompatible version of the MSTest addin.
