### ISSUE TITLE
nuget -  Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by KeKl** [icsharpcode/SharpDevelop#780]
Hi,

while installing the package NUnit3TestAdapter 3.5.0 I get an error. See below.
This also happens on a new created Project.

```
------- Installing...NUnit3TestAdapter 3.5.0 -------
System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.PackageManagement.PackageOperationsResolverFactory.CreateInstallPackageOperationResolver(IPackageRepository localRepository, IPackageRepository sourceRepository, ILogger logger, InstallPackageAction installAction)
   at ICSharpCode.PackageManagement.PackageViewModel.GetInstallOperationsForSolutionPackage(ISolutionPackageRepository solutionRepository, InstallPackageAction installAction, IPackageFromRepository installPackage)
   at ICSharpCode.PackageManagement.PackageViewModel.InstallPackageIntoSolution()
   at ICSharpCode.PackageManagement.PackageViewModel.TryAddingPackage()
==============================
```

**Comment by mrward** [comment]
Looks like there is a bug in the Manage Packages dialog. If you use the Package Management Console you can install the NUnit3TestAdapter NuGet package.

**Comment by KeKl** [comment]
Didn´t tried that. But with the console it´s working.
