### ISSUE TITLE
Sharp Dev. Won't add C# GUI Form to existing solution.

### ISSUE THREAD

**Issue by Dwharf** [icsharpcode/SharpDevelop#784]
Note that there is already a GUI form included in the project, and it is just one panel...

SharpDevelop Version : 4.4.2.9749-39bf891c
.NET Version         : 4.0.30319.42000
OS Version           : Microsoft Windows NT 6.2.9200.0
Current culture      : English (Canada) (en-CA)
Running under WOW6432, processor architecture: x86-64
Working Set Memory   : 149256kb
GC Heap Memory       : 30479kb

Exception thrown:
System.UnauthorizedAccessException: Access to the path 'I:\FinishedSpyVSSpaceAlien\SpyVersusSpaceAlien\WindowsFormsApplication1\SpyVersusSpaceAlien.csproj' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Build.Construction.ProjectRootElement.Save(Encoding saveEncoding)
   at ICSharpCode.SharpDevelop.Project.MSBuildBasedProject.Save(String fileName)
   at ICSharpCode.SharpDevelop.Project.AbstractProject.Save()
   at ICSharpCode.SharpDevelop.Project.Commands.IncludeFileInProject.IncludeFileNode(FileNode fileNode)
   at ICSharpCode.SharpDevelop.Project.DirectoryNode.AddNewFile(String fileName)
   at ICSharpCode.SharpDevelop.Project.Commands.AddNewItemsToProject.AddNewItems()
   at ICSharpCode.SharpDevelop.Project.Commands.AddNewItemsToProject.Run()
   at ICSharpCode.Core.WinForms.MenuCommand.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

---- Recent log messages:
13:53:46.866 [1] DEBUG - ActiveViewContentChanged to [AvalonEditViewContent I:\FinishedSpyVSSpaceAlien\SpyVersusSpaceAlien\WindowsFormsApplication1\Images.Designer.cs]
13:53:46.866 [1] DEBUG - ParseInformationUpdated I:\FinishedSpyVSSpaceAlien\SpyVersusSpaceAlien\WindowsFormsApplication1\Images.Designer.cs new!=null:True
13:54:06.259 [1] DEBUG - ActiveContentChanged to ICSharpCode.SharpDevelop.Project.ProjectBrowserPad
13:54:09.512 [1] INFO - CurrentProject changed to null
13:54:09.528 [1] INFO - Creating default project content
13:54:13.651 [1] DEBUG - Activated feature 'ICSharpCode.SharpDevelop.Project.Commands.AddExistingItemToSolution', activation=Menu
13:54:19.346 [1] INFO - CurrentProject changed to SpyVersusSpaceAlien
13:54:23.560 [1] DEBUG - Activated feature 'ICSharpCode.SharpDevelop.Project.Commands.AddNewItemsToProject', activation=Menu
13:54:45.062 [1] DEBUG - Activated feature 'ICSharpCode.AvalonEdit.AddIn.AvalonEditViewContent/open.cs'
13:54:45.062 [16] DEBUG - Adding existing class Form2 from Form2.cs
13:54:45.062 [16] DEBUG - Creating compound for SpyVersusSpaceAlien.Form2
13:54:45.062 [1] DEBUG - Trying to restore memento of '[AvalonEditViewContent 44119644\Form2.cs]' from key '1e13ec5:44119644\FORM2.CS'
13:54:45.062 [1] DEBUG - ActiveContentChanged to 
13:54:45.062 [1] DEBUG - ActiveWorkbenchWindowChanged to [AvalonWorkbenchWindow: Form2.cs*]
13:54:45.062 [1] DEBUG - ActiveViewContentChanged to 
13:54:45.062 [1] DEBUG - OpenedFileFileNameChange: 44119644\Form2.cs => I:\FinishedSpyVSSpaceAlien\SpyVersusSpaceAlien\WindowsFormsApplication1\Form2.cs
13:54:45.062 [1] INFO - ClearParseInformation: 44119644\Form2.cs
13:54:45.062 [1] DEBUG - Removing part 44119644\Form2.cs from compound class SpyVersusSpaceAlien.Form2
13:54:45.062 [1] DEBUG - Second-to-last part removed (old part count = 2), overwriting compound with last part
13:54:45.062 [18] DEBUG - Adding existing class Form2 from Form2.cs
13:54:45.062 [18] DEBUG - Creating compound for SpyVersusSpaceAlien.Form2
13:54:45.062 [1] DEBUG - Save I:\FinishedSpyVSSpaceAlien\SpyVersusSpaceAlien\WindowsFormsApplication1\Form2.cs
13:54:45.100 [1] DEBUG - ActiveContentChanged to ICSharpCode.SharpDevelop.Project.ProjectBrowserPad
13:54:45.115 [16] DEBUG - Git: OverlayIconManager Thread started
13:54:45.115 [1] ERROR - ThreadException caught
--> Exception:
System.UnauthorizedAccessException: Access to the path 'I:\FinishedSpyVSSpaceAlien\SpyVersusSpaceAlien\WindowsFormsApplication1\SpyVersusSpaceAlien.csproj' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Build.Construction.ProjectRootElement.Save(Encoding saveEncoding)
   at ICSharpCode.SharpDevelop.Project.MSBuildBasedProject.Save(String fileName)
   at ICSharpCode.SharpDevelop.Project.AbstractProject.Save()
   at ICSharpCode.SharpDevelop.Project.Commands.IncludeFileInProject.IncludeFileNode(FileNode fileNode)
   at ICSharpCode.SharpDevelop.Project.DirectoryNode.AddNewFile(String fileName)
   at ICSharpCode.SharpDevelop.Project.Commands.AddNewItemsToProject.AddNewItems()
   at ICSharpCode.SharpDevelop.Project.Commands.AddNewItemsToProject.Run()
   at ICSharpCode.Core.WinForms.MenuCommand.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

---- Post-error application state information:
Installed 3rd party AddIns: 
Workbench.ActiveContent: ICSharpCode.SharpDevelop.Project.ProjectBrowserPad
ProjectService.OpenSolution: [Solution: FileName=I:\FinishedSpyVSSpaceAlien\SpyVersusSpaceAlien\SpyVersusSpaceAlien.sln, HasProjects=True, ReadOnly=False]
ProjectService.CurrentProject: [CSharpProject: SpyVersusSpaceAlien]

**Comment by stefanofraccaro** [comment]
Seems to be a file system exception... add proper file system permission to the folder
