### ISSUE TITLE
An error have occurred

### ISSUE THREAD

**Issue by maria901** [icsharpcode/SharpDevelop#844]
SharpDevelop Version : 5.1.0.5216-0e58df71
.NET Version         : 4.7.03062
OS Version           : Microsoft Windows NT 6.1.7601 Service Pack 1
Current culture      : Portuguese (Brazil) (pt-BR)
Current UI language  : en
Running under WOW6432, processor architecture: x86-64
Working Set Memory   : 167120kb
GC Heap Memory       : 62861kb

Exception thrown:
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at ICSharpCode.Svn.Commands.RegisterEventsCommand.TreeNodeCreated(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeViewEventHandler.Invoke(Object sender, TreeViewEventArgs e)
   at ICSharpCode.SharpDevelop.Project.AbstractProjectBrowserTreeNode.Refresh()
   at ICSharpCode.SharpDevelop.Gui.ExtTreeNode.Insert(Int32 index, TreeNode parentNode)
   at ICSharpCode.SharpDevelop.Gui.ExtTreeNode.InsertSorted(TreeNode parentNode)
   at ICSharpCode.SharpDevelop.Project.DirectoryNode.Initialize()
   at ICSharpCode.SharpDevelop.Project.AbstractProjectBrowserTreeNode.Expanding()
   at ICSharpCode.SharpDevelop.Project.DirectoryNode.Expanding()
   at ICSharpCode.SharpDevelop.Gui.ExtTreeView.OnBeforeExpand(TreeViewCancelEventArgs e)

---- Recent log messages:
01:06:28.293 [1] DEBUG - ProjectBrowser: Tree view handle created, will load [Solution C:\AMANDA AVA KOCI PEREIRA\nosso_trabalho\amanda_projects\AmandaRicardo_Locacao Diaria\AmandaRicardo _ ABBA\arab_cd\arab_cd\samararicardo_c#_soc\LocaçãoDeTemporada\LocaçãodeTemporada\LocaçãodeTemporada.sln with 1 projects].
01:06:28.792 [1] DEBUG - ProjectBrowser: Loading solution [Solution C:\AMANDA AVA KOCI PEREIRA\nosso_trabalho\amanda_projects\AmandaRicardo_Locacao Diaria\AmandaRicardo _ ABBA\arab_cd\arab_cd\samararicardo_c#_soc\LocaçãoDeTemporada\LocaçãodeTemporada\LocaçãodeTemporada.sln with 1 projects] into project tree view
01:06:29.716 [1] INFO - Loading addin F# Binding
01:06:29.761 [5] DEBUG - Git: OverlayIconManager Thread started
01:06:30.193 [5] DEBUG - Git: OverlayIconManager Thread finished
01:06:30.575 [1] INFO - Loading addin WiX Binding
01:06:30.778 [5] DEBUG - Git: OverlayIconManager Thread started
01:06:30.902 [1] DEBUG - [AddInManager2.Events] Package list download ended (success: True).
01:06:31.010 [1] DEBUG - NavigationService -- suspend logging
01:06:31.010 [1] DEBUG - NavigationService -- resume logging
01:06:31.080 [5] DEBUG - Git: OverlayIconManager Thread finished
01:06:31.151 [1] DEBUG - Service startup: ICSharpCode.UnitTesting.ITestService
01:06:46.237 [9] DEBUG - Service startup: ICSharpCode.SharpDevelop.Workbench.IShutdownService
01:06:47.140 [13] DEBUG - Serializing to C:\Users\AAKP\AppData\Local\Temp\SharpDevelop5.1\Microsoft.VisualBasic.cb2491f4.dat
01:06:57.693 [16] DEBUG - Serializing to C:\Users\AAKP\AppData\Local\Temp\SharpDevelop5.1\System.Web.d13d98db.dat
01:07:02.240 [LoadSolutionProjects] DEBUG - LocaçãodeTemporada: ParseFiles() finished. 0 files were re-used from CC cache; 170 files were parsed (170 of those are serializable)
01:07:02.256 [LoadSolutionProjects] DEBUG - LoadSolutionProjectsThread finished after 00:00:43.5334465
01:07:02.263 [1] DEBUG - Service startup: ICSharpCode.SharpDevelop.Workbench.IDisplayBindingService
01:07:17.894 [1] INFO - CurrentProject changed to LocaçãodeTemporada
01:07:17.969 [1] INFO - Initialize DirectoryNode C:\AMANDA AVA KOCI PEREIRA\nosso_trabalho\amanda_projects\AmandaRicardo_Locacao Diaria\AmandaRicardo _ ABBA\arab_cd\arab_cd\samararicardo_c#_soc\LocaçãoDeTemporada\LocaçãodeTemporada\LocaçãodeTemporada
01:07:17.984 [13] DEBUG - Git: OverlayIconManager Thread started
01:07:19.082 [1] ERROR - 
--> Exception:
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at ICSharpCode.Svn.Commands.RegisterEventsCommand.TreeNodeCreated(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeViewEventHandler.Invoke(Object sender, TreeViewEventArgs e)
   at ICSharpCode.SharpDevelop.Project.AbstractProjectBrowserTreeNode.Refresh()
   at ICSharpCode.SharpDevelop.Gui.ExtTreeNode.Insert(Int32 index, TreeNode parentNode)
   at ICSharpCode.SharpDevelop.Gui.ExtTreeNode.InsertSorted(TreeNode parentNode)
   at ICSharpCode.SharpDevelop.Project.DirectoryNode.Initialize()
   at ICSharpCode.SharpDevelop.Project.AbstractProjectBrowserTreeNode.Expanding()
   at ICSharpCode.SharpDevelop.Project.DirectoryNode.Expanding()
   at ICSharpCode.SharpDevelop.Gui.ExtTreeView.OnBeforeExpand(TreeViewCancelEventArgs e)
01:07:19.423 [13] ERROR - 
--> Exception:
System.IO.PathTooLongException: O caminho especificado, o nome do arquivo ou ambos são muito longos. O nome de arquivo totalmente qualificado deve ter menos de 260 caracteres e o nome do diretório menos de 248 caracteres.
   em System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   em System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   em System.IO.Path.InternalGetDirectoryName(String path)
   em System.IO.Path.GetDirectoryName(String path)
   em ICSharpCode.GitAddIn.Git.FindWorkingCopyRoot(String fileName)
   em ICSharpCode.GitAddIn.GitStatusCache.GetFileStatus(String fileName)
   em ICSharpCode.GitAddIn.OverlayIconManager.RunStep(AbstractProjectBrowserTreeNode node)
   em ICSharpCode.GitAddIn.OverlayIconManager.Run(Object state)
01:07:19.840 [13] WARN - Stack trace of last exception log:
   em System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   em System.Environment.get_StackTrace()
   em ICSharpCode.SharpDevelop.Logging.SDMessageService.ShowException(Exception ex, String message)
   em ICSharpCode.Core.MessageService.ShowException(Exception ex, String message)
   em ICSharpCode.GitAddIn.OverlayIconManager.Run(Object state)
   em System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   em System.Threading.ThreadPoolWorkQueue.Dispatch()
   em System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
01:07:20.258 [1] WARN - Stack trace of last exception log:
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at ICSharpCode.SharpDevelop.Logging.SDMessageService.ShowException(Exception ex, String message)
   at ICSharpCode.SharpDevelop.Gui.ExtTreeView.OnBeforeExpand(TreeViewCancelEventArgs e)
   at System.Windows.Forms.TreeView.TvnExpanding(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.Control.SendMessage(Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.Control.ReflectMessageInternal(IntPtr hWnd, Message& m)
   at System.Windows.Forms.Control.WmNotify(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Control.DefWndProc(Message& m)
   at System.Windows.Forms.TreeView.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at ICSharpCode.SharpDevelop.Workbench.WorkbenchStartup.Run(IList`1 fileList)
   at ICSharpCode.SharpDevelop.Sda.CallHelper.RunWorkbenchInternal(Object settings)
   at ICSharpCode.SharpDevelop.Sda.CallHelper.RunWorkbench(WorkbenchSettings settings)
   at ICSharpCode.SharpDevelop.Sda.SharpDevelopHost.RunWorkbench(WorkbenchSettings settings)
   at ICSharpCode.SharpDevelop.Startup.SharpDevelopMain.RunApplication()
   at ICSharpCode.SharpDevelop.Startup.SharpDevelopMain.Run()
   at ICSharpCode.SharpDevelop.Startup.SharpDevelopMain.Main(String[] args)

---- Post-error application state information:
Installed 3rd party AddIns: 
ProjectService.CurrentSolution: [Solution C:\AMANDA AVA KOCI PEREIRA\nosso_trabalho\amanda_projects\AmandaRicardo_Locacao Diaria\AmandaRicardo _ ABBA\arab_cd\arab_cd\samararicardo_c#_soc\LocaçãoDeTemporada\LocaçãodeTemporada\LocaçãodeTemporada.sln with 1 projects]
ProjectService.CurrentProject: [CSharpProject: LocaçãodeTemporada]
Workbench.ActiveContent: ICSharpCode.SharpDevelop.Project.Converter.UpgradeViewContent

I hope this help

Ricardo & Amanda

**Comment by maria901** [comment]
fixed, the path was too long, now it is working, sorry for the problem

Amanda
